-- =========================================================
-- Garantias iniciais (Supabase / Postgres)
-- =========================================================
CREATE SCHEMA IF NOT EXISTS public;

GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO public;
GRANT ALL ON SCHEMA public TO anon;
GRANT ALL ON SCHEMA public TO authenticated;
GRANT ALL ON SCHEMA public TO service_role;

SET search_path TO public;

-- =========================================================
-- Schema interno para funções (evita erro PGRST002)
-- =========================================================
CREATE SCHEMA IF NOT EXISTS internal;

-- =========================================================
-- Tabela: a001_dispensacoes
-- =========================================================
CREATE TABLE IF NOT EXISTS public.a001_dispensacoes (
    a001_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Origem da captura
    a001_site TEXT NOT NULL,
    a001_url  TEXT NOT NULL,
    a001_tipo TEXT NOT NULL DEFAULT 'formulario_dispensacao',
    a001_coletado_em TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Receita
    a001_cod_receita TEXT NOT NULL,
    a001_data_receita DATE,

    -- Estabelecimento / Operador
    a001_estabelecimento_saude TEXT,
    a001_operador TEXT,

    -- Paciente
    a001_codigo_paciente TEXT NOT NULL,
    a001_cod_cartao_sus VARCHAR(20),
    a001_paciente_nome TEXT,
    a001_paciente_nascimento DATE,
    a001_observacao TEXT,

    -- Médico
    a001_medico_crm VARCHAR(20),
    a001_medico_nome TEXT,
    a001_nmr_conselho VARCHAR(20),

    -- Origem da receita
    a001_codigo_origem_receita TEXT,
    a001_local_origem_receita TEXT,
    a001_cod_subgrupo_origem_receita TEXT,
    a001_subgrupo_local_origem_receita TEXT,

    -- Auditoria
    a001_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    a001_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT unq_paciente_receita
        UNIQUE (a001_codigo_paciente, a001_cod_receita, a001_site)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_dispensacoes_paciente
    ON public.a001_dispensacoes (a001_codigo_paciente);

CREATE INDEX IF NOT EXISTS idx_dispensacoes_receita
    ON public.a001_dispensacoes (a001_cod_receita);

CREATE INDEX IF NOT EXISTS idx_dispensacoes_site_data
    ON public.a001_dispensacoes (a001_site, a001_data_receita);

-- =========================================================
-- Trigger function a001 (schema interno)
-- =========================================================
CREATE OR REPLACE FUNCTION internal.set_updated_at_a001()
RETURNS trigger AS $$
BEGIN
    NEW.a001_updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_set_updated_at_a001
ON public.a001_dispensacoes;

CREATE TRIGGER trg_set_updated_at_a001
BEFORE UPDATE ON public.a001_dispensacoes
FOR EACH ROW
EXECUTE FUNCTION internal.set_updated_at_a001();

-- =========================================================
-- Tabela: a002_dispensacao_itens
-- =========================================================
CREATE TABLE IF NOT EXISTS public.a002_dispensacao_itens (
    a002_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    a002_dispensacao_id_a001 BIGINT NOT NULL
        REFERENCES public.a001_dispensacoes(a001_id)
        ON DELETE CASCADE,

    -- Produto
    a002_codigo_produto TEXT,
    a002_formula_produto TEXT NOT NULL,

    -- Posologia
    a002_qt_dose NUMERIC(10,2) NOT NULL CHECK (a002_qt_dose > 0),
    a002_forma_consumo TEXT,
    a002_frequencia INTEGER NOT NULL CHECK (a002_frequencia > 0),
    a002_duracao_tratam_dia INTEGER NOT NULL CHECK (a002_duracao_tratam_dia > 0),
    a002_nmr_dias_dispensar INTEGER NOT NULL CHECK (a002_nmr_dias_dispensar > 0),

    -- Ordem do item na dispensação
    a002_item_index INTEGER NOT NULL CHECK (a002_item_index >= 0),

    -- Auditoria
    a002_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    a002_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT unq_item_por_dispensacao
        UNIQUE (a002_dispensacao_id_a001, a002_item_index)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_a002_dispensacao
    ON public.a002_dispensacao_itens (a002_dispensacao_id_a001);

CREATE INDEX IF NOT EXISTS idx_a002_codigo_produto
    ON public.a002_dispensacao_itens (a002_codigo_produto);

-- =========================================================
-- Trigger function a002 (schema interno)
-- =========================================================
CREATE OR REPLACE FUNCTION internal.set_updated_at_a002()
RETURNS trigger AS $$
BEGIN
    NEW.a002_updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_set_updated_at_a002
ON public.a002_dispensacao_itens;

CREATE TRIGGER trg_set_updated_at_a002
BEFORE UPDATE ON public.a002_dispensacao_itens
FOR EACH ROW
EXECUTE FUNCTION internal.set_updated_at_a002();

-- =========================================================
-- Permissões nas tabelas
-- =========================================================
-- Concede permissões nas tabelas para usuários anônimos e autenticados
GRANT ALL ON public.a001_dispensacoes TO anon;
GRANT ALL ON public.a001_dispensacoes TO authenticated;
GRANT ALL ON public.a001_dispensacoes TO service_role;

GRANT ALL ON public.a002_dispensacao_itens TO anon;
GRANT ALL ON public.a002_dispensacao_itens TO authenticated;
GRANT ALL ON public.a002_dispensacao_itens TO service_role;

-- Concede permissão de uso nas sequences (para IDENTITY)
-- As sequences são criadas automaticamente pelo PostgreSQL quando usamos GENERATED BY DEFAULT AS IDENTITY
-- Execute este comando no Supabase SQL Editor após criar as tabelas para verificar os nomes:
-- SELECT sequence_name FROM information_schema.sequences WHERE sequence_schema = 'public' AND sequence_name LIKE '%a001%' OR sequence_name LIKE '%a002%';
--
-- Depois, execute os GRANTs com os nomes corretos das sequences, por exemplo:
-- GRANT USAGE ON SEQUENCE public.a001_dispensacoes_a001_id_seq TO anon, authenticated, service_role;
-- GRANT USAGE ON SEQUENCE public.a002_dispensacao_itens_a002_id_seq TO anon, authenticated, service_role;

-- =========================================================
-- Políticas RLS (Row Level Security)
-- =========================================================
-- Habilita RLS nas tabelas
ALTER TABLE public.a001_dispensacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.a002_dispensacao_itens ENABLE ROW LEVEL SECURITY;

-- Políticas para a001_dispensacoes
-- Permite SELECT para todos
CREATE POLICY "Permitir SELECT em a001_dispensacoes"
ON public.a001_dispensacoes
FOR SELECT
TO anon, authenticated, service_role
USING (true);

-- Permite INSERT para todos
CREATE POLICY "Permitir INSERT em a001_dispensacoes"
ON public.a001_dispensacoes
FOR INSERT
TO anon, authenticated, service_role
WITH CHECK (true);

-- Permite UPDATE para todos
CREATE POLICY "Permitir UPDATE em a001_dispensacoes"
ON public.a001_dispensacoes
FOR UPDATE
TO anon, authenticated, service_role
USING (true)
WITH CHECK (true);

-- Permite DELETE para todos (opcional - ajuste conforme necessário)
CREATE POLICY "Permitir DELETE em a001_dispensacoes"
ON public.a001_dispensacoes
FOR DELETE
TO anon, authenticated, service_role
USING (true);

-- Políticas para a002_dispensacao_itens
-- Permite SELECT para todos
CREATE POLICY "Permitir SELECT em a002_dispensacao_itens"
ON public.a002_dispensacao_itens
FOR SELECT
TO anon, authenticated, service_role
USING (true);

-- Permite INSERT para todos
CREATE POLICY "Permitir INSERT em a002_dispensacao_itens"
ON public.a002_dispensacao_itens
FOR INSERT
TO anon, authenticated, service_role
WITH CHECK (true);

-- Permite UPDATE para todos
CREATE POLICY "Permitir UPDATE em a002_dispensacao_itens"
ON public.a002_dispensacao_itens
FOR UPDATE
TO anon, authenticated, service_role
USING (true)
WITH CHECK (true);

-- Permite DELETE para todos (opcional - ajuste conforme necessário)
CREATE POLICY "Permitir DELETE em a002_dispensacao_itens"
ON public.a002_dispensacao_itens
FOR DELETE
TO anon, authenticated, service_role
USING (true);
